import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';

@Component({
  selector: 'app-hr-leave-request-modal',
  templateUrl: './hr-leave-request-modal.component.html',
  styleUrls: ['./hr-leave-request-modal.component.css']
})
export class HrLeaveRequestModalComponent implements OnInit {
  isLoading: boolean = false;
  showConfirmation: boolean = false;
  
  // Variables to store data
  leaveType: string = '';
  employeeId: string = '';

  constructor(
    private route: ActivatedRoute,
    private router: Router
  ) {}

  ngOnInit(): void {
    // Get the leave type from route parameters
    this.route.paramMap.subscribe(params => {
      const leaveTypeParam = params.get('leaveType');
      
      if (leaveTypeParam) {
        // Convert URL-friendly format back to readable format
        this.leaveType = leaveTypeParam.replace(/-/g, ' ');
        
        // Convert to title case
        this.leaveType = this.leaveType
          .split(' ')
          .map(word => word.charAt(0).toUpperCase() + word.slice(1))
          .join(' ');
      } else {
        console.error('No leave type parameter found');
        // Redirect back if no parameter
        this.router.navigate(['/dashboard/leave-summary']);
      }
    });

    // Get employee ID from localStorage
    this.employeeId = localStorage.getItem('employeeId') || '';
    
    if (!this.employeeId) {
      console.error('Employee ID not found in localStorage');
      this.router.navigate(['/login']);
    }
  }

  // Get today's date in YYYY-MM-DD format
  getTodayDate(): string {
    return new Date().toISOString().split('T')[0];
  }

  // Get a default end date (7 days from now for example)
  getDefaultEndDate(): string {
    const date = new Date();
    date.setDate(date.getDate() + 7);
    return date.toISOString().split('T')[0];
  }

  // Show confirmation modal
  onSubmit(): void {
    this.showConfirmation = true;
  }

  // Confirm and submit
  confirmSubmit(): void {
    this.showConfirmation = false;
    this.isLoading = true;
    
    // Create default leave request data
    const leaveRequestData = {
      employeeId: this.employeeId,
      leaveType: this.leaveType,
      fromDate: this.getTodayDate(),
      toDate: this.getDefaultEndDate(),
      reason: `Standard ${this.leaveType} request`,
      contactNumber: 'Not specified',
      status: 'pending',
      submittedDate: new Date().toISOString(),
      autoGenerated: true
    };

    console.log('Leave request submitted:', leaveRequestData);
    
    // Here you would typically call your API service
    // this.apiService.submitLeaveRequest(leaveRequestData).subscribe({
    //   next: (response) => {
    //     this.isLoading = false;
    //     alert(`${this.leaveType} request submitted successfully!`);
    //     this.router.navigate(['/dashboard/leave-summary']);
    //   },
    //   error: (error) => {
    //     this.isLoading = false;
    //     alert('Error submitting leave request. Please try again.');
    //   }
    // });

    // Simulate API call for now
    setTimeout(() => {
      this.isLoading = false;
      alert(`${this.leaveType} request submitted successfully!`);
      this.router.navigate(['/dashboard/leave-summary']);
    }, 1500);
  }

  // Cancel and go back
  onCancel(): void {
    this.router.navigate(['/dashboard/leave-summary']);
  }
}